# http://www.smartjava.org/content/minimal-kafka-instance-for-k8s/
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: leader
      port: 3888
  selector:
    app: zookeeper

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: main
          image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo
          readinessProbe:
            tcpSocket:
              port: 2181
  serviceName: zookeeper